# SPDX-FileCopyrightText: The memoization.java Authors
# SPDX-License-Identifier: 0BSD

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - sebhoss
